//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok_421.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id_Application { get; set; }
        public int id_Manager { get; set; }
        public int id_Agent { get; set; }
        public int id_Product { get; set; }
        public Nullable<System.DateTime> DateApplication { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Products Products { get; set; }
    }
}
