//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok_421.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Application = new HashSet<Application>();
            this.Products_Material = new HashSet<Products_Material>();
        }
    
        public int id_Product { get; set; }
        public string Name_Product { get; set; }
        public string Article { get; set; }
        public Nullable<int> MinPriceForAgent { get; set; }
        public string Image { get; set; }
        public int id_Type_Product { get; set; }
        public Nullable<int> QuantityPeople { get; set; }
        public string NumberProduction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Material> Products_Material { get; set; }
        public virtual Type_Products Type_Products { get; set; }
    }
}
